2021-07-08 20:45:45,395 ERROR [C:\Users\daisu\Documents\py\django\mysite\mysite\middleware.py:16] Unknown field(s) ('password1', 'password2') specified for AppUser. Check fields/fieldsets/exclude attributes of class UserAdmin.
Traceback (most recent call last):
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\contrib\admin\options.py", line 710, in get_form
    return modelform_factory(self.model, **defaults)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\forms\models.py", line 563, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\forms\models.py", line 276, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) ('password1', 'password2') specified for AppUser

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\contrib\admin\options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\contrib\admin\sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\views\decorators\debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\contrib\auth\admin.py", line 99, in add_view
    return self._add_view(request, form_url, extra_context)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\contrib\auth\admin.py", line 126, in _add_view
    return super().add_view(request, form_url, extra_context)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\contrib\admin\options.py", line 1657, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\contrib\admin\options.py", line 1540, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\contrib\admin\options.py", line 1574, in _changeform_view
    ModelForm = self.get_form(
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\contrib\auth\admin.py", line 80, in get_form
    return super().get_form(request, obj, **defaults)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\contrib\admin\options.py", line 712, in get_form
    raise FieldError(
django.core.exceptions.FieldError: Unknown field(s) ('password1', 'password2') specified for AppUser. Check fields/fieldsets/exclude attributes of class UserAdmin.
