2021-07-08 20:45:03,452 ERROR [C:\Users\daisu\Documents\py\django\mysite\mysite\middleware.py:16] 'fields'
Traceback (most recent call last):
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\contrib\admin\options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\contrib\admin\sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\views\decorators\debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\contrib\auth\admin.py", line 99, in add_view
    return self._add_view(request, form_url, extra_context)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\contrib\auth\admin.py", line 126, in _add_view
    return super().add_view(request, form_url, extra_context)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\contrib\admin\options.py", line 1657, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\contrib\admin\options.py", line 1540, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\contrib\admin\options.py", line 1575, in _changeform_view
    request, obj, change=not add, fields=flatten_fieldsets(fieldsets)
  File "C:\Users\daisu\anaconda3\envs\djangoenv\lib\site-packages\django\contrib\admin\utils.py", line 99, in flatten_fieldsets
    flatten(opts['fields'])
KeyError: 'fields'
